version: "3.7"
services:
    app:
        container_name: twill-cms-blog-app-dev
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        image: ejklock/php-fpm-node:8.1
        ports:
            - 8080:8080

        networks:
            - twill-cms-blogNetwork
        restart: unless-stopped
        volumes:
            - ./:/var/www/app
            - ./docker-compose/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        working_dir: /var/www/app
    db:
        command: --default-authentication-plugin=mysql_native_password
        container_name: twill-cms-blog-dev-db
        environment:
            MYSQL_DATABASE: twill-cms-blog
            MYSQL_PASSWORD: twill-cms-blog
            MYSQL_ROOT_PASSWORD: twill-cms-blog
            MYSQL_USER: twill-cms-blog
            SERVICE_NAME: mysql
            SERVICE_TAGS: dev
        image: mysql:5.7
        networks:
            - twill-cms-blogNetwork
        ports:
            - 33306:3306
        restart: unless-stopped
        tty: true
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
            - twill-cms-blogMysqlData:/var/lib/mysql
    nginx:
        container_name: twill-cms-blog-dev-nginx
        image: nginx:alpine
        networks:
            - twill-cms-blogNetwork
        ports:
            - 8000:80
        restart: unless-stopped
        volumes:
            - ./:/var/www/app
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        working_dir: /var/www/app
networks:
    twill-cms-blogNetwork:
        driver: bridge
volumes:
    twill-cms-blogMysqlData:
        driver: local
        name: twill-cms-blogMysqlData
